### ISSUE TITLE
Support for ciphergroupname

### ISSUE THREAD

**Issue by olljanat** [citrix/terraform-provider-netscaler#49]
Unfortunately even `ns_default_ssl_profile_secure_frontend` profile is not secure anymore so we need someway to hardening cipher settings:
- https://blog.qualys.com/technology/2019/04/22/zombie-poodle-and-goldendoodle-vulnerabilities
- https://support.citrix.com/article/CTX240139

I think that adding support for ciphergroupname to csvserver and lbvserver would be simplest way to solve it.

**Comment by olljanat** [comment]
@chiradeep @giorgos-nikolopoulos PTAL

**Comment by giorgos-nikolopoulos** [comment]
This is an update to let you know we are working on this issue.

I will be implementing a new attribute named `ciphers` which will be a list of strings specifying the ciphers to be used with the particular ssl vserver.

Order of the ciphers will be important since it will be the order of preference for the ssl vserver.

I chose to go with `ciphers` because there is some complexity as to what kind of entity can be bound to the ssl vserver.

In ADC there are cipher suites which are the most elementary setting entities that define how to perform an SSL handshake. You can view them by running in the nscli `show ciphersuite`.
Then there are ciphergroups which are ordered lists of ciphersuites which can be shown with `show cipher`. Furthermore the user can define its own cipher groups.

In the bindings to the ssl vserver both types are acceptable values. So instead of going with either name I chose to go with the one I thought was more generic, `ciphers`

**Comment by olljanat** [comment]
@giorgos-nikolopoulos thanks but can you also publish new version which contains this one?

**Comment by giorgos-nikolopoulos** [comment]
@olljanat Just uploaded the new [release](https://github.com/citrix/terraform-provider-netscaler/releases/tag/v0.12.0)
